import Head from "next/head";
import { Inter } from "@next/font/google";
import { Button } from "../components/Button";
import { Header } from "../components/Header";
import { Card } from "../components/Card";
import { Banner } from "../components/Banner";
import { Skeleton } from "../components/Skeleton";
import { ResultCard } from "../components/ResultCard";
import { GridSection } from "../components/GridSection";
import { Footer } from "../components/Footer";
import { ShareForm } from "../components/forms/ShareForm";
import { Dialog } from "../components/Dialog";
import { SocialMediaButtons } from "../components/SocialMediaButtons";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isDialogVisible, setIsDialogVisible] = useState(false);

  const domain = "example.com";

  return (
    <>
      <Head>
        <title>Next Tailwind App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Dialog
          title="Share DNS"
          onClose={() => setIsDialogVisible(false)}
          visible={isDialogVisible}
        >
          <ShareForm />

          <Button
            className="my-0 mx-auto"
            size="lg"
            onClick={() => console.log("Send Invited")}
          >
            Send Invited
          </Button>
          <SocialMediaButtons />
        </Dialog>

        {/* <Skeleton width="w-12" />
          <Skeleton color="bg-primary-500" /> */}

        <div className="mb-0 mt-2xl mx-auto p-xl max-w-screen-lg rounded-md border-2 border-neutral-50">
          <h2 className="text-center italic font-medium text-xl text-neutral-900 pb-md">
            {domain}
          </h2>

          <Banner image="/images/google-domains.png" />

          <GridSection
            title="How do you want to update your DNS?"
            padding="py-lg"
          >
            <Card
              title="Update for me"
              description="You just need to log in, we will update your DNS automatically"
              variant="primary"
              withIcon
            />
            <Card
              title="Add DNS Manually"
              description="Follow our tutorial to update your DNS manually"
              variant="secondary"
              withIcon
            />
          </GridSection>

          <section className="flex justify-between items-center py-lg border-t border-b border-neutral-50">
            <p>Want to send these to a friend/colleague to do for you?</p>
            <Button withIcon onClick={() => setIsDialogVisible(true)}>
              Share
            </Button>
          </section>

          <GridSection
            title="Are you a PRO at DNS? Update these records:"
            padding="pt-lg"
          >
            <ResultCard type="A" value="104.248.56.174" name="@" />
            <ResultCard type="CNAME" value="ssl.trady.com" name="www" />
          </GridSection>
        </div>
      </main>

      <Footer />
    </>
  );
}
