import Head from "next/head";
import { Inter } from "@next/font/google";
import { Button } from "../components/Button";
import { Header } from "../components/Header";
import { Card } from "../components/Card";
import { Banner } from "../components/Banner";
import { Layout } from "../components/Layout";
import { Skeleton } from "../components/Skeleton";
import { ResultCard } from "../components/ResultCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const domain = "example.com";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Header />

          {/* <Skeleton width="w-12" />
          <Skeleton color="bg-primary-500" /> */}

          <div className="rounded-md border-2 border-neutral-50 p-xl">
            <h2 className="text-center italic font-medium text-xl text-neutral-900 pb-md">
              {domain}
            </h2>

            <Banner image="/images/google-domains.png" />

            <section className="py-lg">
              {/* TODO: same card list component with subtitle */}
              <h3 className="text-neutral-600 pb-xs">
                How do you want to update your DNS?
              </h3>
              {/* <h3 className="italic text-neutral-900 font-medium text-lg">
                {domain}
              </h3> */}
              <section className="grid grid-cols-2 gap-y-5 gap-x-8 pb-lg">
                <Card
                  title="Update for me"
                  description="You just need to log in, we will update your DNS automatically"
                  variant="primary"
                />
                <Card
                  title="Add DNS Manually"
                  description="Follow our tutorial to update your DNS manually"
                  variant="secondary"
                />
              </section>
            </section>

            <section className="flex justify-between items-center py-lg border-t border-b border-neutral-50">
              <p>Want to send these to a friend/colleague to do for you?</p>
              <Button onClick={() => {}}>Share</Button>
            </section>

            {/* TODO: same card list component with subtitle */}
            <section className="pt-lg">
              <h3 className="text-neutral-600 pb-xs">
                Are you a PRO at DNS? Update these records:
              </h3>
              <section className="grid grid-cols-2  gap-y-5 gap-x-8">
                <ResultCard type="A" value="104.248.56.174" name="@" />
                <ResultCard type="CNAME" value="ssl.trady.com" name="www" />
              </section>
            </section>
          </div>
        </Layout>
      </main>
    </>
  );
}
